import { getLoginSession } from '@/lib/auth/auth';
import { GetServerSideProps, NextApiRequest } from 'next';
import Head from 'next/head';

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const getSession = await getLoginSession(ctx.req as NextApiRequest);

    console.log(getSession);

    if (!getSession) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        };
    }

    return {
        props: {},
    };
};

const Home = () => {
    return (
        <>
            <Head>
                <title>Dashboard Template</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Welcome to Dashboard Template</h1>
            </main>
        </>
    );
};

export default Home;
